import type { WorkerProfile, ProviderProfile, Job, Application, Notification, User } from '../types';

export const DISTRICTS = [
  'Kathmandu', 'Lalitpur', 'Bhaktapur', 'Pokhara', 'Biratnagar',
  'Birgunj', 'Dharan', 'Butwal', 'Hetauda', 'Bharatpur', 'Dhangadhi', 'Nepalgunj'
];

export const ALL_SKILLS = [
  'Electrical Wiring', 'Plumbing', 'Carpentry', 'Masonry', 'Welding',
  'Computer Repair', 'Network Setup', 'IT Support', 'Data Entry', 'Typing',
  'Cooking', 'Baking', 'Barista', 'Waiter Service', 'Kitchen Helper',
  'Driving (LMV)', 'Driving (HMV)', 'Forklift Operation',
  'Event Setup', 'Crowd Management', 'Security Guard',
  'Teaching', 'English Language', 'Maths Tutoring',
  'Nursing', 'First Aid', 'Patient Care',
  'Accounting', 'Bookkeeping', 'Tally ERP',
  'Sales', 'Customer Service', 'Reception',
  'Tailoring', 'Stitching', 'Embroidery',
  'Solar Installation', 'Generator Maintenance', 'Panel Installation',
  'Graphic Design', 'Photography', 'Video Editing',
  'Physical Labour', 'Loading/Unloading', 'Cleaning',
];

export const demoWorkerUser: User = {
  id: 'u-w-001',
  role: 'worker',
  email: 'aarav@example.com',
  name: 'Aarav Sharma',
  profileId: 'wp-001',
};

export const demoProviderUser: User = {
  id: 'u-p-001',
  role: 'provider',
  email: 'himtech@example.com',
  name: 'HimTech Solutions',
  profileId: 'pp-001',
};

export const workerProfiles: WorkerProfile[] = [
  {
    id: 'wp-001',
    name: 'Aarav Sharma',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format',
    phone: '+977-9841234567',
    email: 'aarav@example.com',
    location: 'Baneshwor, Kathmandu',
    district: 'Kathmandu',
    skills: ['Electrical Wiring', 'Panel Installation', 'Solar Installation', 'Generator Maintenance'],
    qualifications: [
      {
        id: 'q-001',
        degree: 'Diploma in Electrical Engineering',
        institution: 'CTEVT, Kathmandu',
        year: 2019,
        field: 'Electrical Engineering',
      }
    ],
    experience: [
      {
        id: 'e-001',
        title: 'Junior Electrician',
        company: 'Reliable Power Services',
        duration: '2019 – 2022 (3 years)',
        description: 'Handled residential and commercial electrical wiring, panel installations, and generator maintenance across Kathmandu Valley.',
      },
      {
        id: 'e-002',
        title: 'Freelance Electrician',
        company: 'Self-employed',
        duration: '2022 – Present',
        description: 'Independent contracts for solar installations, rewiring, and industrial electrical work.',
      }
    ],
    availableDates: ['2024-03-10', '2024-03-11', '2024-03-12', '2024-03-15', '2024-03-18', '2024-03-19', '2024-03-20'],
    availability: 'flexible',
    bio: 'Certified electrician with 5+ years of experience in residential, commercial, and solar installations. Reliable, safety-conscious, and skilled in modern wiring systems. Available for flexible work across Kathmandu Valley.',
    workHistory: [
      {
        jobId: 'j-008',
        jobTitle: 'Electrician for Office Renovation',
        providerName: 'HimTech Solutions',
        date: 'Feb 2024',
        payment: 4000,
        rating: 5,
        review: 'Excellent work. Very professional and completed ahead of schedule.',
      },
      {
        jobId: 'j-009',
        jobTitle: 'Solar Panel Installation',
        providerName: 'Green Energy Nepal',
        date: 'Jan 2024',
        payment: 6000,
        rating: 5,
        review: 'Great attention to detail. Would hire again.',
      },
      {
        jobId: 'j-010',
        jobTitle: 'Event Lighting Setup',
        providerName: 'Green Valley Events',
        date: 'Dec 2023',
        payment: 2500,
        rating: 4,
        review: 'Good work, arrived on time.',
      },
    ],
    rating: 4.8,
    totalJobs: 23,
    verified: false,
  },
  {
    id: 'wp-002',
    name: 'Priya Thapa',
    photo: 'https://images.unsplash.com/photo-1494790108755-2616b612b17c?w=200&h=200&fit=crop&auto=format',
    phone: '+977-9856789012',
    email: 'priya@example.com',
    location: 'Lakeside, Pokhara',
    district: 'Pokhara',
    skills: ['Event Setup', 'Customer Service', 'Reception', 'Waiter Service'],
    qualifications: [
      {
        id: 'q-002',
        degree: 'Bachelor in Hotel Management',
        institution: 'Ace Institute of Management, Pokhara',
        year: 2021,
        field: 'Hospitality Management',
      }
    ],
    experience: [
      {
        id: 'e-003',
        title: 'Event Coordinator',
        company: 'Fishtail Lodge, Pokhara',
        duration: '2021 – 2023',
        description: 'Coordinated corporate and wedding events, managed front desk operations.',
      }
    ],
    availableDates: ['2024-03-10', '2024-03-14', '2024-03-15', '2024-03-16'],
    availability: 'full-day',
    bio: 'Hospitality professional with experience in event coordination and hotel management. Fluent in English, Nepali, and Hindi.',
    workHistory: [],
    rating: 4.6,
    totalJobs: 11,
    verified: false,
  },
  {
    id: 'wp-003',
    name: 'Bikram Rai',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&auto=format',
    phone: '+977-9812345678',
    email: 'bikram@example.com',
    location: 'Kumaripati, Lalitpur',
    district: 'Lalitpur',
    skills: ['IT Support', 'Computer Repair', 'Network Setup', 'Data Entry'],
    qualifications: [
      {
        id: 'q-003',
        degree: 'BIT (Bachelor of Information Technology)',
        institution: 'Tribhuvan University, Kathmandu',
        year: 2020,
        field: 'Information Technology',
      }
    ],
    experience: [
      {
        id: 'e-004',
        title: 'IT Support Technician',
        company: 'TechMandu Pvt Ltd',
        duration: '2020 – 2023',
        description: 'Provided hardware/software support, network configuration, and end-user training.',
      }
    ],
    availableDates: ['2024-03-10', '2024-03-11', '2024-03-15', '2024-03-18'],
    availability: 'flexible',
    bio: 'IT professional with 3 years of experience in technical support and network administration. Quick learner and problem solver.',
    workHistory: [],
    rating: 4.9,
    totalJobs: 7,
    verified: false,
  },
  {
    id: 'wp-004',
    name: 'Sita Gurung',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&auto=format',
    phone: '+977-9823456789',
    email: 'sita@example.com',
    location: 'Bharatpur-10, Chitwan',
    district: 'Bharatpur',
    skills: ['Nursing', 'Patient Care', 'First Aid'],
    qualifications: [
      {
        id: 'q-004',
        degree: 'Proficiency Certificate in Nursing (PCN)',
        institution: 'Nobel Medical College, Biratnagar',
        year: 2018,
        field: 'Nursing',
      }
    ],
    experience: [
      {
        id: 'e-005',
        title: 'Staff Nurse',
        company: 'Bharatpur Hospital',
        duration: '2018 – 2023',
        description: 'Ward nursing, patient monitoring, medication administration in general ward.',
      }
    ],
    availableDates: ['2024-03-10', '2024-03-11', '2024-03-12', '2024-03-13'],
    availability: 'morning',
    bio: 'Experienced nurse with 5 years in hospital settings. Compassionate, reliable, and trained in emergency response.',
    workHistory: [],
    rating: 4.7,
    totalJobs: 5,
    verified: false,
  },
];

export const providerProfiles: ProviderProfile[] = [
  {
    id: 'pp-001',
    orgName: 'HimTech Solutions Pvt. Ltd.',
    logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&h=200&fit=crop&auto=format',
    contactName: 'Sanjay Manandhar',
    email: 'himtech@example.com',
    phone: '+977-014512678',
    location: 'New Baneshwor, Kathmandu',
    district: 'Kathmandu',
    industry: 'Information Technology',
    description: 'HimTech Solutions is a leading IT services company providing software development, IT support, and digital transformation services to businesses across Nepal.',
    verified: true,
    verifiedDate: '2023-08-15',
    pan: '301456789',
    totalHires: 48,
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: 'pp-002',
    orgName: 'Himalayan Grand Hotel',
    logo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=200&h=200&fit=crop&auto=format',
    contactName: 'Rekha Shrestha',
    email: 'himalayangrand@example.com',
    phone: '+977-061234567',
    location: 'Lakeside, Pokhara',
    district: 'Pokhara',
    industry: 'Hospitality & Tourism',
    description: 'A 4-star hotel at the shores of Phewa Lake offering world-class hospitality. We regularly hire flexible staff for events, peak seasons, and special occasions.',
    verified: true,
    verifiedDate: '2023-06-20',
    pan: '402378901',
    totalHires: 112,
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: 'pp-003',
    orgName: 'Green Valley Events Pvt. Ltd.',
    logo: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=200&h=200&fit=crop&auto=format',
    contactName: 'Roshan KC',
    email: 'greenvalley@example.com',
    phone: '+977-9801234567',
    location: 'Pulchowk, Lalitpur',
    district: 'Lalitpur',
    industry: 'Events & Entertainment',
    description: 'Premier event management company specializing in weddings, corporate events, and cultural programs across the Kathmandu Valley.',
    verified: true,
    verifiedDate: '2023-09-10',
    pan: '501234567',
    totalHires: 245,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 'pp-004',
    orgName: 'Nepal Infrastructure Corporation',
    logo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop&auto=format',
    contactName: 'Dinesh Basnet',
    email: 'nepali@example.com',
    phone: '+977-014234567',
    location: 'Balaju, Kathmandu',
    district: 'Kathmandu',
    industry: 'Construction',
    description: 'Mid-size construction company handling residential and commercial projects across Nepal. Regularly needing skilled and unskilled labor on project basis.',
    verified: false,
    pan: '601234567',
    totalHires: 78,
    rating: 4.2,
    reviewCount: 24,
  },
  {
    id: 'pp-005',
    orgName: 'Bharatpur Medical Center',
    logo: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=200&h=200&fit=crop&auto=format',
    contactName: 'Dr. Anita Poudel',
    email: 'bharatpur@example.com',
    phone: '+977-056123456',
    location: 'Bharatpur-10, Chitwan',
    district: 'Bharatpur',
    industry: 'Healthcare',
    description: 'A 100-bed private hospital providing comprehensive healthcare services in Chitwan. We hire qualified medical professionals and support staff.',
    verified: true,
    verifiedDate: '2023-07-01',
    pan: '701234567',
    totalHires: 34,
    rating: 4.9,
    reviewCount: 22,
  },
];

export const initialJobs: Job[] = [
  {
    id: 'j-001',
    providerId: 'pp-001',
    providerName: 'HimTech Solutions Pvt. Ltd.',
    providerLogo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'IT Support Technician — Software Launch Event',
    description: 'We are hosting a major software product launch event and need experienced IT support technicians to manage on-site technical setup, troubleshoot hardware/software issues, and ensure seamless presentation systems. The event will host 200+ attendees including press and corporate clients.',
    category: 'skill-based',
    skillsRequired: ['IT Support', 'Computer Repair', 'Network Setup'],
    qualificationRequired: 'At least +2 with IT background or diploma',
    experienceRequired: 'Minimum 1 year IT support experience',
    workType: 'full-day',
    workersNeeded: 3,
    workersHired: 1,
    date: '2024-03-15',
    startTime: '07:00',
    endTime: '20:00',
    duration: '1 day (13 hours)',
    location: 'Hotel Annapurna, Durbar Marg, Kathmandu',
    district: 'Kathmandu',
    payment: 2500,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-02',
    deadline: '2024-03-12',
    applicantCount: 5,
  },
  {
    id: 'j-002',
    providerId: 'pp-003',
    providerName: 'Green Valley Events Pvt. Ltd.',
    providerLogo: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Event Setup & Hospitality Staff — Grand Wedding',
    description: 'Seeking energetic and presentable staff for a grand wedding reception at Hyatt Regency Kathmandu. Roles include reception, table service, guest guidance, and event breakdown. Full training will be provided on the morning of the event.',
    category: 'beginner-friendly',
    skillsRequired: ['Event Setup', 'Customer Service', 'Waiter Service'],
    qualificationRequired: 'SLC/SEE passed preferred but not mandatory',
    experienceRequired: 'No prior experience needed, attitude matters',
    workType: 'full-day',
    workersNeeded: 20,
    workersHired: 12,
    date: '2024-03-18',
    startTime: '10:00',
    endTime: '22:00',
    duration: '1 day',
    location: 'Hyatt Regency Kathmandu, Boudha',
    district: 'Kathmandu',
    payment: 900,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-03',
    deadline: '2024-03-15',
    applicantCount: 34,
  },
  {
    id: 'j-003',
    providerId: 'pp-002',
    providerName: 'Himalayan Grand Hotel',
    providerLogo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Front Desk Receptionist — Holi Season Cover',
    description: 'We need experienced front desk staff to cover our peak Holi season rush. Responsibilities include check-in/check-out, guest queries, phone handling, and coordination with housekeeping. Uniform and meals provided.',
    category: 'skill-based',
    skillsRequired: ['Reception', 'Customer Service', 'English Language'],
    qualificationRequired: "Bachelor's degree or Hotel Management diploma",
    experienceRequired: 'Minimum 1 year front desk or hospitality experience',
    workType: 'multi-day',
    workersNeeded: 2,
    workersHired: 0,
    date: '2024-03-20',
    endDate: '2024-03-26',
    startTime: '08:00',
    endTime: '20:00',
    duration: '7 days',
    location: 'Lakeside, Pokhara',
    district: 'Pokhara',
    payment: 1800,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-04',
    deadline: '2024-03-17',
    applicantCount: 8,
  },
  {
    id: 'j-004',
    providerId: 'pp-004',
    providerName: 'Nepal Infrastructure Corporation',
    providerLogo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=80&h=80&fit=crop&auto=format',
    providerVerified: false,
    title: 'Construction Labourer — Residential Project',
    description: 'Looking for reliable unskilled and semi-skilled labourers for a residential apartment complex under construction in Patan. Work involves mixing concrete, carrying materials, scaffolding support, and general site assistance. Safety equipment provided.',
    category: 'beginner-friendly',
    skillsRequired: ['Physical Labour', 'Loading/Unloading'],
    qualificationRequired: 'No formal qualification required',
    experienceRequired: 'No experience required, physically fit individuals welcome',
    workType: 'multi-day',
    workersNeeded: 15,
    workersHired: 8,
    date: '2024-03-11',
    endDate: '2024-04-10',
    startTime: '07:00',
    endTime: '17:00',
    duration: '30 days',
    location: 'Mangal Bazar, Patan, Lalitpur',
    district: 'Lalitpur',
    payment: 1200,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-01',
    deadline: '2024-03-14',
    applicantCount: 22,
  },
  {
    id: 'j-005',
    providerId: 'pp-005',
    providerName: 'Bharatpur Medical Center',
    providerLogo: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Staff Nurse — Emergency Ward Cover',
    description: 'Qualified nursing staff needed to cover our Emergency Ward for a 2-week period while permanent staff are on training leave. Requires NMC registration and experience with emergency patient care, IV administration, and vitals monitoring.',
    category: 'qualified',
    skillsRequired: ['Nursing', 'Patient Care', 'First Aid'],
    qualificationRequired: 'PCN or B.Sc. Nursing, NMC Registration mandatory',
    experienceRequired: 'Minimum 2 years hospital experience',
    workType: 'multi-day',
    workersNeeded: 2,
    workersHired: 0,
    date: '2024-03-18',
    endDate: '2024-03-31',
    startTime: '08:00',
    endTime: '20:00',
    duration: '14 days',
    location: 'Bharatpur-10, Chitwan',
    district: 'Bharatpur',
    payment: 3000,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-05',
    deadline: '2024-03-16',
    applicantCount: 6,
  },
  {
    id: 'j-006',
    providerId: 'pp-003',
    providerName: 'Green Valley Events Pvt. Ltd.',
    providerLogo: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Event Lighting & Electrical Technician',
    description: 'Need an experienced electrician/electrical technician to handle event lighting setup, power distribution, and electrical safety for a large corporate gala event at Soaltee Hotel. Involves working with stage lighting, LED systems, and backup power coordination.',
    category: 'skill-based',
    skillsRequired: ['Electrical Wiring', 'Panel Installation', 'Generator Maintenance'],
    qualificationRequired: 'Diploma or certificate in Electrical Engineering',
    experienceRequired: 'At least 2 years experience in event or industrial electrical work',
    workType: 'full-day',
    workersNeeded: 2,
    workersHired: 0,
    date: '2024-03-22',
    startTime: '06:00',
    endTime: '23:00',
    duration: '1 day (17 hours)',
    location: 'Soaltee Hotel, Tahachal, Kathmandu',
    district: 'Kathmandu',
    payment: 3500,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-06',
    deadline: '2024-03-19',
    applicantCount: 3,
  },
  {
    id: 'j-007',
    providerId: 'pp-001',
    providerName: 'HimTech Solutions Pvt. Ltd.',
    providerLogo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Data Entry & Documentation Operator',
    description: 'Short-term data entry project for digitizing and organizing client records. Work involves typing from scanned documents into our database system. Good typing speed (30+ WPM) and accuracy required. Work can be done at our Baneshwor office.',
    category: 'skill-based',
    skillsRequired: ['Data Entry', 'Typing', 'Computer Repair'],
    qualificationRequired: '+2 or above',
    experienceRequired: 'Some computer experience preferred',
    workType: 'multi-day',
    workersNeeded: 4,
    workersHired: 2,
    date: '2024-03-12',
    endDate: '2024-03-14',
    startTime: '09:00',
    endTime: '17:00',
    duration: '3 days',
    location: 'New Baneshwor, Kathmandu',
    district: 'Kathmandu',
    payment: 1200,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-04',
    deadline: '2024-03-11',
    applicantCount: 11,
  },
  {
    id: 'j-008',
    providerId: 'pp-004',
    providerName: 'Nepal Infrastructure Corporation',
    providerLogo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=80&h=80&fit=crop&auto=format',
    providerVerified: false,
    title: 'Licensed Electrician — Commercial Building',
    description: 'Looking for a qualified electrician for complete electrical work on a 3-storey commercial building in Balaju. Work includes main panel installation, conduit wiring, socket/switch installation, and earthing. Materials provided by client.',
    category: 'skill-based',
    skillsRequired: ['Electrical Wiring', 'Panel Installation', 'Solar Installation'],
    qualificationRequired: 'Diploma or CTEVT certificate in Electrical work',
    experienceRequired: 'Minimum 3 years experience, license preferred',
    workType: 'multi-day',
    workersNeeded: 1,
    workersHired: 1,
    date: '2024-02-20',
    endDate: '2024-03-05',
    startTime: '08:00',
    endTime: '17:00',
    duration: '14 days',
    location: 'Balaju, Kathmandu',
    district: 'Kathmandu',
    payment: 2200,
    paymentType: 'per-day',
    status: 'filled',
    postedDate: '2024-02-10',
    deadline: '2024-02-18',
    applicantCount: 4,
  },
  {
    id: 'j-009',
    providerId: 'pp-002',
    providerName: 'Himalayan Grand Hotel',
    providerLogo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Head Cook — Nepali & Continental Cuisine',
    description: 'Seeking an experienced head cook for our hotel restaurant to cover during a temporary staff shortage. Must be skilled in preparing both traditional Nepali dal-bhat thali and Continental dishes. Opportunity to lead a team of 3 kitchen helpers.',
    category: 'skill-based',
    skillsRequired: ['Cooking', 'Kitchen Helper', 'Baking'],
    qualificationRequired: 'Hotel Management or Catering certificate preferred',
    experienceRequired: 'Minimum 3 years as head/senior cook in a restaurant or hotel',
    workType: 'multi-day',
    workersNeeded: 1,
    workersHired: 0,
    date: '2024-03-14',
    endDate: '2024-03-28',
    startTime: '07:00',
    endTime: '19:00',
    duration: '15 days',
    location: 'Lakeside, Pokhara',
    district: 'Pokhara',
    payment: 2000,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-05',
    deadline: '2024-03-12',
    applicantCount: 7,
  },
  {
    id: 'j-010',
    providerId: 'pp-005',
    providerName: 'Bharatpur Medical Center',
    providerLogo: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=80&h=80&fit=crop&auto=format',
    providerVerified: true,
    title: 'Medical Records Clerk — Data Digitization',
    description: 'Short-term contract to digitize paper medical records into our hospital management system. Basic computer skills and understanding of medical terminology required. Full confidentiality agreement required.',
    category: 'qualified',
    skillsRequired: ['Data Entry', 'Typing'],
    qualificationRequired: 'Healthcare or IT background preferred',
    experienceRequired: '1+ year data entry or healthcare clerical experience',
    workType: 'multi-day',
    workersNeeded: 2,
    workersHired: 0,
    date: '2024-03-13',
    endDate: '2024-03-22',
    startTime: '09:00',
    endTime: '17:00',
    duration: '10 days',
    location: 'Bharatpur-10, Chitwan',
    district: 'Bharatpur',
    payment: 1500,
    paymentType: 'per-day',
    status: 'active',
    postedDate: '2024-03-04',
    deadline: '2024-03-12',
    applicantCount: 4,
  },
];

export const initialApplications: Application[] = [
  {
    id: 'app-001',
    jobId: 'j-001',
    workerId: 'wp-001',
    workerName: 'Aarav Sharma',
    workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Baneshwor, Kathmandu',
    workerSkills: ['Electrical Wiring', 'Panel Installation', 'Solar Installation', 'Generator Maintenance'],
    workerRating: 4.8,
    workerTotalJobs: 23,
    jobTitle: 'IT Support Technician — Software Launch Event',
    providerName: 'HimTech Solutions Pvt. Ltd.',
    providerId: 'pp-001',
    appliedDate: '2024-03-05',
    status: 'shortlisted',
    coverNote: 'I have strong technical skills and experience with event setups. While my background is primarily electrical, I also have solid IT support experience from working on corporate sites where I handled both power and network infrastructure.',
  },
  {
    id: 'app-002',
    jobId: 'j-006',
    workerId: 'wp-001',
    workerName: 'Aarav Sharma',
    workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Baneshwor, Kathmandu',
    workerSkills: ['Electrical Wiring', 'Panel Installation', 'Solar Installation', 'Generator Maintenance'],
    workerRating: 4.8,
    workerTotalJobs: 23,
    jobTitle: 'Event Lighting & Electrical Technician',
    providerName: 'Green Valley Events Pvt. Ltd.',
    providerId: 'pp-003',
    appliedDate: '2024-03-08',
    status: 'accepted',
    coverNote: 'Event electrical work is my specialty. I have handled lighting setups for 10+ corporate events across Kathmandu. I am familiar with stage lighting systems, LED arrays, and backup generator coordination.',
    providerNote: 'Great profile! Looking forward to working with you.',
  },
  {
    id: 'app-003',
    jobId: 'j-002',
    workerId: 'wp-001',
    workerName: 'Aarav Sharma',
    workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Baneshwor, Kathmandu',
    workerSkills: ['Electrical Wiring', 'Panel Installation', 'Solar Installation', 'Generator Maintenance'],
    workerRating: 4.8,
    workerTotalJobs: 23,
    jobTitle: 'Event Setup & Hospitality Staff — Grand Wedding',
    providerName: 'Green Valley Events Pvt. Ltd.',
    providerId: 'pp-003',
    appliedDate: '2024-03-04',
    status: 'rejected',
    coverNote: 'I am available on this date and can assist with general event setup work.',
    providerNote: 'We need hospitality experience for this role.',
  },
  {
    id: 'app-004',
    jobId: 'j-001',
    workerId: 'wp-003',
    workerName: 'Bikram Rai',
    workerPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Kumaripati, Lalitpur',
    workerSkills: ['IT Support', 'Computer Repair', 'Network Setup', 'Data Entry'],
    workerRating: 4.9,
    workerTotalJobs: 7,
    jobTitle: 'IT Support Technician — Software Launch Event',
    providerName: 'HimTech Solutions Pvt. Ltd.',
    providerId: 'pp-001',
    appliedDate: '2024-03-03',
    status: 'accepted',
    coverNote: 'I am an IT professional with 3 years of experience in technical support. I have provided on-site IT support for 5+ corporate events and am very familiar with AV setups and network configuration.',
  },
  {
    id: 'app-005',
    jobId: 'j-001',
    workerId: 'wp-002',
    workerName: 'Priya Thapa',
    workerPhoto: 'https://images.unsplash.com/photo-1494790108755-2616b612b17c?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Lakeside, Pokhara',
    workerSkills: ['Event Setup', 'Customer Service', 'Reception', 'Waiter Service'],
    workerRating: 4.6,
    workerTotalJobs: 11,
    jobTitle: 'IT Support Technician — Software Launch Event',
    providerName: 'HimTech Solutions Pvt. Ltd.',
    providerId: 'pp-001',
    appliedDate: '2024-03-06',
    status: 'pending',
    coverNote: 'I have experience coordinating technology setups at large events from my work at Fishtail Lodge.',
  },
  {
    id: 'app-006',
    jobId: 'j-005',
    workerId: 'wp-004',
    workerName: 'Sita Gurung',
    workerPhoto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&auto=format',
    workerLocation: 'Bharatpur-10, Chitwan',
    workerSkills: ['Nursing', 'Patient Care', 'First Aid'],
    workerRating: 4.7,
    workerTotalJobs: 5,
    jobTitle: 'Staff Nurse — Emergency Ward Cover',
    providerName: 'Bharatpur Medical Center',
    providerId: 'pp-005',
    appliedDate: '2024-03-07',
    status: 'pending',
    coverNote: 'I am an experienced nurse with 5 years in hospital ward settings including emergency response. I hold a valid NMC license and am available for the full 14-day period.',
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'n-001',
    userId: 'u-w-001',
    type: 'selection',
    title: 'Application Accepted!',
    message: 'Green Valley Events accepted your application for "Event Lighting & Electrical Technician". The event is on March 22nd at Soaltee Hotel.',
    date: '2024-03-09',
    read: false,
    jobId: 'j-006',
    applicationId: 'app-002',
  },
  {
    id: 'n-002',
    userId: 'u-w-001',
    type: 'shortlisted',
    title: 'You\'ve been Shortlisted',
    message: 'HimTech Solutions shortlisted your application for "IT Support Technician". They will review final candidates and notify you soon.',
    date: '2024-03-07',
    read: false,
    jobId: 'j-001',
    applicationId: 'app-001',
  },
  {
    id: 'n-003',
    userId: 'u-w-001',
    type: 'rejection',
    title: 'Application Update',
    message: 'Your application for "Event Setup & Hospitality Staff" was not selected this time. Green Valley Events noted: "We need hospitality experience for this role."',
    date: '2024-03-06',
    read: true,
    jobId: 'j-002',
    applicationId: 'app-003',
  },
  {
    id: 'n-004',
    userId: 'u-w-001',
    type: 'new-job',
    title: 'New Job Matching Your Skills',
    message: 'A new job "Electrician for Hospital Backup Power" in Kathmandu matches your electrical skills. NPR 3,200/day. Apply before March 14.',
    date: '2024-03-08',
    read: true,
  },
  {
    id: 'n-005',
    userId: 'u-p-001',
    type: 'application',
    title: 'New Applicant',
    message: 'Aarav Sharma has applied for "IT Support Technician — Software Launch Event". Review their profile now.',
    date: '2024-03-05',
    read: false,
    jobId: 'j-001',
    applicationId: 'app-001',
  },
  {
    id: 'n-006',
    userId: 'u-p-001',
    type: 'application',
    title: 'New Applicant',
    message: 'Bikram Rai has applied for "IT Support Technician — Software Launch Event". They have strong IT support experience.',
    date: '2024-03-03',
    read: true,
    jobId: 'j-001',
    applicationId: 'app-004',
  },
];

export function computeMatchScore(job: Job, worker: WorkerProfile): { score: number; reasons: string[] } {
  const reasons: string[] = [];
  let score = 0;

  const matchedSkills = job.skillsRequired.filter(s =>
    worker.skills.some(ws => ws.toLowerCase() === s.toLowerCase())
  );
  if (matchedSkills.length > 0) {
    const skillScore = Math.round((matchedSkills.length / job.skillsRequired.length) * 40);
    score += skillScore;
    reasons.push(`${matchedSkills.length} of ${job.skillsRequired.length} required skills match (${matchedSkills.join(', ')})`);
  }

  if (worker.district === job.district) {
    score += 25;
    reasons.push(`Located in ${job.district} — same district as the job`);
  } else if (worker.district === 'Kathmandu' && job.district === 'Lalitpur') {
    score += 15;
    reasons.push('Adjacent district — easy commute');
  } else if (worker.district === 'Lalitpur' && job.district === 'Kathmandu') {
    score += 15;
    reasons.push('Adjacent district — easy commute');
  }

  if (worker.availableDates.includes(job.date)) {
    score += 20;
    reasons.push(`Available on ${new Date(job.date).toLocaleDateString('en-NP', { month: 'short', day: 'numeric' })}`);
  }

  if (worker.totalJobs > 10) {
    score += 10;
    reasons.push(`Experienced worker — ${worker.totalJobs} completed jobs`);
  } else if (worker.totalJobs > 0) {
    score += 5;
    reasons.push(`${worker.totalJobs} completed jobs on the platform`);
  }

  if (worker.rating >= 4.5) {
    score += 5;
    reasons.push(`High rating: ${worker.rating}★`);
  }

  return { score: Math.min(score, 100), reasons };
}
